force-app/main/default/objects/Manager__c/Manager__c.object-meta.xml
<CustomObject>
    <label>Manager</label>
    <nameField>
        <label>Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserDetail__c/UserDetail__c.object-meta.xml
<CustomObject>
    <label>UserDetail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserDetail__c/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UserDetail__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserDetail__c/fields/Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Manager_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Name</label>
    <referenceTo>Manager__c</referenceTo>
    <relationshipLabel>User Details</relationshipLabel>
    <relationshipName>User_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserDetail__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <label>password</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserDetail__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <label>username</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SignupController.cls
public with sharing class SignupController {
    @AuraEnabled
    public static void createUser(String name, String username, String password, String email, String role, Integer age, Date birthday, Date joiningDate, string ManagerName,Boolean isManager) {
        UserDetail__c newUser = new UserDetail__c();
        newUser.Name = name;
        newUser.Username__c = username;
        newUser.Password__c = password;
        newUser.Email__c = email;
        newUser.Role__c = role;
        newUser.Age__c = age;
        newUser.Birthday__c = birthday;
        newUser.Joining_Date__c = joiningDate;
        newUser.Manager_Name__c=ManagerName;
        newUser.Manager__c=isManager;
        insert newUser;
        sendWelcomeEmail(email);
        if (isManager==true){
            Manager__c manager =new Manager__c();
            manager.Name=name;
            manager.Email__c=email;
            insert manager;
        }
    }
    @future (callout=true)
    public static void sendWelcomeEmail(String userEmail) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[] { userEmail });
        email.setSubject('Welcome to Our Platform!');
        email.setPlainTextBody('Thank you for signing up. We’re excited to have you on board.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
    }
    @AuraEnabled
    public static List<Manager__c> getManagers(){
        
        List<Manager__c> manager= [SELECT Id,Name FROM Manager__c];
       
        return manager;
       
    }

}