force-app/main/default/objects/High_Value_Opportunity_Log__c/High_Value_Opportunity_Log__c.object-meta.xml
<CustomObject>
    <label>High Value Opportunity Log</label>
    <nameField>
        <label>High Value Opportunity Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>High Value Opportunity Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/High_Value_Opportunity_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>High Value Opportunity Logs</relationshipLabel>
    <relationshipName>High_Value_Opportunity_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/High_Value_Opportunity_Log__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Id</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>High Value Opportunity Logs</relationshipLabel>
    <relationshipName>High_Value_Opportunity_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/High_Value_Opportunity_Log__c/fields/Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Time_Stamp__c</fullName>
    <label>Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/HighValueOpportunity.cls
public class HighValueOpportunity {
    public static void updateAccount(List<Opportunity> newList){
        List<High_Value_Opportunity_Log__c> logs = new List<High_Value_Opportunity_Log__c>();
        set<Id> accountsIdstoUpdate=new set<Id>();
        if (newList!=null){
            for(Opportunity opp :newList){
                if(opp.amount>50000){
            		accountsIdstoUpdate.add(opp.AccountId);
                    System.debug('accountsIdstoUpdate'+accountsIdstoUpdate);
                    High_Value_Opportunity_Log__c log =new High_Value_Opportunity_Log__c(
                         Opportunity_Id__c=opp.Id,
                         Opportunity_Name__c=opp.Name,
                         Account__c=opp.AccountId,
                         OwnerId=opp.OwnerId,
                         Amount__c=opp.Amount,
                         Time_Stamp__c=System.now()
                    );
                    logs.add(log);
          
                }
            }
        }
        if (!accountsIdstoUpdate.isEmpty()) {
        	List<Account> accountsToUpdate = [SELECT Id, High_Value_Customer__c FROM Account WHERE Id IN :accountsIdstoUpdate];
        	for (Account acc : accountsToUpdate) {
            	acc.High_Value_Customer__c = true;
        	}
        	update accountsToUpdate;
    	}
        if(!logs.isEmpty()){
            insert logs;
        }
        
    }

}