force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IsOverdue__c.field-meta.xml
<CustomField>
    <fullName>IsOverdue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsOverdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InvoiceTriggerHandler.cls
public class InvoiceTriggerHandler {
    public static void InvoiceHandler(List<Invoice__c> newList){
        for (Invoice__c i: newList){
            System.debug('newRecorddate'+i.DueDate__c);
            System.debug('newRecorddate'+i.Status__c);
            if (i.DueDate__c!=null && i.Status__c!='Paid' && i.DueDate__c<Date.today()){
                i.IsOverdue__c=True;
            }else{
                i.IsOverdue__c=False;
            }
        }
    }

}